version: '2'
volumes:
    node-red-data:
    homeassistant-data:
services:
  ttn:
    build: ttn
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:stable
    environment:
      - "TZ=Europe/Zurich"
    volumes:
      - homeassistant-data:/config
    ports:
      - 8123:8123
    restart: always
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  mqtt-broker:
    image: panuwitp/mosquitto-arm
    ports:
      - '1883:1883'
  node-red:
    build: node-red
    environment:
      - TZ=Europe/Zurich
    volumes:
       - 'node-red-data:/data'
    ports:
       - '1880:1880'
    depends_on:
        - mqtt-broker
    restart: always
  nginx:
    build : nginx
    depends_on:
      - node-red
    ports:
       - '80:80'
       - '443:443'
    restart: always
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    ports:
      - '9090:9090'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'