version: '2'
volumes:
    influx-data:
    influx-config:
    telegraf-config:
services:
  influxdb:
    image: arm32v7/influxdb:latest
    volumes:
      # Mount for influxdb data directory
      - 'influx-data:/var/lib/influxdb'
      # Mount for influxdb configuration
      - 'influx-config:/etc/influxdb/'
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089"
    restart: always
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: arm32v7/telegraf:latest
    volumes:
      # Mount for telegraf configuration
       - 'telegraf-config:/etc/telegraf'
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    depends_on:
      - influxdb
    restart: always
  grafana:
    image: fg2it/grafana-armhf:v5.1.4
    ports:
       - "3000:3000"
    links:
       - influxdb
    restart: always

