version: '2'
volumes:
    influx-data:
    influx-config:
services:
  influxdb:
    image: arm32v7/influxdb:latest
    volumes:
      # Mount for influxdb data directory
      - 'influx-data:/var/lib/influxdb'
      # Mount for influxdb configuration
      - 'influx-config:/etc/influxdb/'
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089"
    restart: always
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build : telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    depends_on:
      - influxdb
    restart: always
  grafana:
    build: grafana
    ports:
       - "3000:3000"
    links:
       - influxdb
    restart: always
  nginx:
    image: tobi312/rpi-nginx
    depends_on:
      - grafana
    links:
      - grafana
    ports:
       - "80:80"
       - "443:443"
    restart: always

